### ISSUE TITLE
Does MongoDB toolkit support Streams v4.0?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.mongoDB#4]
We have the following query on the Streams forum.

https://developer.ibm.com/answers/questions/190295/used-mongodb-toolkit-sucessfully/?smartspace=streamsdev

Customer has the following error:
In file included from /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/bson/optime.h:23, from /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/db/jsobj.h:34, from /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/client/dbclientinterface.h:29, from /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/client/connpool.h:22, from /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/client/dbclient.h:40, from src/operator/./RawData_MongoD.h:10, from src/operator/RawData_MongoD.cpp:3: /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/util/concurrency/mutex.h: In function ‘streams_boost::xtime mongo::incxtimemillis(long long int)’: /opt/ibm/InfoSphere_Streams/4.0.0.0/toolkits/com.ibm.streamsx.mongodb/impl/include/mongo/util/concurrency/mutex.h:50: error: ‘TIME_UTC’ is not a member of ‘boost’ make: *** [build/operator/RawData_MongoD.o] Error 1 CDISP0141E ERROR: The compilation of the generated code failed.

**Comment by leongor** [comment]
Actually the problem wasn't related to Streams 4.0, but to internal boost version check.
I've fixed it. Please, update me if it works now.
