### ISSUE TITLE
Add support user level authentication

### ISSUE THREAD

**Issue by hardeys** [IBMStreams/streamsx.mongoDB#5]
It will be great to have user level authentication feature added to the toolkit while inserting and querying data from MongoDB

**Comment by leongor** [comment]
I'm evaluating the authentication methods MongoDB supports. If you have some preferred ones - please suggest.

**Comment by hardeys** [comment]
Hi, we would prefer to use new default method "SCRAM-SHA-1" for verion 3 of MongoDB

**Comment by leongor** [comment]
Added in v.1.3.0 - closing the issue.
