### ISSUE TITLE
Question:  What happens when my attribute is already formatted as JSON?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.mongoDB#8]
Hi there,

I am looking at the mongoDB toolkit.  I am interested in using the insert operator to insert some JSON document into my MongoDB database.  In my understanding, the insert operator translates a SPL tuple to BSON and insert it as documents into MongoDB.  What happens if I have an attribute that is a rstring formatted in JSON already, can I still use the insert operator to insert the document into the DB?  Is this use case satisfied?

Thanks....
Samantha

**Comment by leongor** [comment]
@chanskw This functionality is implemented in `Query` operator (`QueryDocumentFieldAsJson`), but not in `Insert` operator. I think it can be added too - going to check it.

**Comment by chanskw** [comment]
@leongor thank you!

**Comment by leongor** [comment]
@chanskw I've added `InsertDocumentAsJson` and `Up(date/sert)Document(s)AsJson` custom
output functions with samples. Please, run some tests.

**Comment by leongor** [comment]
Added the solution to the [v2.0.1](https://github.com/IBMStreams/streamsx.mongoDB/releases/tag/v2.0.1).
Closing the issue.
